Fix compilation error: use .other instead of .general for IncidentType
- Changed default IncidentType from .general to .other
- IncidentType enum doesn't have a .general case
- This fixes the 'Type IncidentType has no member general' compilation error
- Scheduled alerts should now compile and work correctly